//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveReader3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiveReader3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (() =&gt; {
        ///    const Text = (element) =&gt; {
        ///        let txt = &quot;&quot;;
        ///        if (element !== null) {
        ///            element.childNodes.forEach(function myFunction(node) {
        ///                if (node.nodeType === 3) { // is a text node
        ///                    txt += node.nodeValue;
        ///                }
        ///            });
        ///        }
        ///        return txt.replace(/\s+/g, &apos; &apos;).trim();
        ///    }
        ///    const TextAll = (element) =&gt; {
        ///        let txt = (element === null) ? &quot;&quot; : element.textContent;
        ///        return (txt === null) ? &quot;&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FlashScore_v2 {
            get {
                return ResourceManager.GetString("FlashScore_v2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (() =&gt; {
        ///    /** Delete empty fields from object */
        ///    const removeEmpty = (o) =&gt; {
        ///        Object.keys(o).forEach(k =&gt; !o[k] ? delete o[k] : {});
        ///        return o;
        ///    }
        ///    /** Convert all whitespace to sigle-space */
        ///    const textLine = (text) =&gt; {
        ///        return text?.replace(/\s/g, &apos; &apos;).replace(/\s{2,}/g, &apos; &apos;).trim() || &apos;&apos;;
        ///    }
        ///    /** Remove all whitespace */
        ///    const textSolid = (text) =&gt; {
        ///        return text?.replace(/\s/g, &apos;&apos;) || &apos;&apos;;
        ///    }
        ///    /** Match start time */
        ///    const  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FlashScorePopup {
            get {
                return ResourceManager.GetString("FlashScorePopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
